### ISSUE TITLE
module lazy not found

### ISSUE THREAD

**Issue by onezhaoyn** [nvim-lua/kickstart.nvim#192]
**Describe the bug**
open nvim , showing 'module `lazy` not found'

<img width="1140" alt="iShot_2023-02-22_07 34 46" src="https://user-images.githubusercontent.com/30831076/220484221-f95db093-e15a-44d9-a2eb-a01226e6e315.png">

It turned out that for Lazy nvim plugin, there are following system requirements:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/30831076/220484468-50a9528a-98d1-4d81-87e0-30c66ebca4d5.png">

And my git version is 2.15.0, after i installed the latest git, no error anymore

**Desktop (please complete the following information):**
- OS: MacOS 12
- Terminal: iTerm2

**Comment by AIGeneratedUsername** [comment]
# Reproducible sample
## Dockerfile

```Dockerfile
ENV DEBIAN_FRONTEND noninteractive
# Set image locale.
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en

ARG USERNAME=nonroot
ARG USER_UID=1000
ARG USER_GID=$USER_UID
# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    # Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update \
    # NvChad dependencies: ripgrep, build-essential, neovim
    && apt-get install -y \
    curl \
    fzf \
    ripgrep \
    tree \
    git \
    xclip \
    nodejs \
    npm \
    wget \
    build-essential \
    && wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb \
    && apt-get install ./nvim-linux64.deb \
    && rm ./nvim-linux64.deb \
    && rm -rf /var/lib/apt/lists/*

USER $USERNAME
RUN \
    # Install NvChad.
    git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
```
## Docker Compose

```yaml
services:
  backend:
    build:
      context: .
      cache_to:
        - type=local,dest=${HOME}/.cache/docker_compose_local,mode=max
      cache_from:
        - type=local,src=${HOME}/.cache/docker_compose_local
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - config_nvim:/home/nonroot/.config/nvim
      - local_share_nvim:/home/nonroot/.local/share/nvim
      - cache:/home/nonroot/.cache
      # Persist bash history https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
      - container-bashhistory:/commandhistory
    tty: true

volumes:
  config_nvim:
  local_share_nvim:
  cache:
  container-bashhistory:
```
## Run with commands
1. `docker compose up -d --build`
2. `docker exec -it neovim_docker-backend-1 bash`
3. `nvim`
